export const brandingData = {
  title: "InMailly Team Branding Guide — LinkedIn Presence",
  headlines: [
    "Helping Businesses Grow Through Strategic LinkedIn Outreach",
    "B2B Lead Generation Specialist | Connecting Businesses with Decision-Makers",
    "Growth Marketing Professional | Lead Generation & LinkedIn Outreach",
    "Helping SaaS Companies Generate Qualified Leads Through Targeted Outreach",
    "Business Development & Demand Generation Specialist | B2B Growth",
    "Building High-Value Business Relationships Through LinkedIn",
    "Lead Generation Expert | Managing High-Performance Outreach Campaigns",
    "Growth-Focused B2B Marketer | Turning Cold Outreach Into Warm Conversations",
  ],
  jobTitles: [
    "Marketing Specialist",
    "Growth Marketing Executive",
    "Lead Generation Specialist",
    "Business Development Executive",
    "Outreach Campaign Manager",
    "LinkedIn Marketing Specialist",
    "Demand Generation Executive",
    "B2B Marketing Executive",
    "Account Development Representative",
    "Sales Development Representative (SDR)",
    "Client Acquisition Specialist",
    "Growth Consultant",
  ],
  about:
    "I help businesses connect with the right decision-makers and generate qualified pipeline through strategic LinkedIn outreach and relationship-driven prospecting. My work spans lead generation, campaign management, prospect research, LinkedIn marketing, and business development — all focused on turning cold connections into real conversations and real opportunities.",
  company:
    "InMailly helps businesses build a stronger professional presence and connect with the clients they actually want — through LinkedIn-focused marketing, targeted outreach, and lead generation. We handle the research, the positioning, the campaigns, and the conversations so our clients can focus on closing.",
  skills: [
    "Lead Generation",
    "LinkedIn Marketing",
    "Business Development",
    "B2B Marketing",
    "Prospect Research",
    "Sales Prospecting",
    "Client Acquisition",
    "Outreach Campaigns",
    "Demand Generation",
    "Relationship Building",
    "Social Selling",
    "CRM Management",
    "Digital Marketing",
    "Growth Marketing",
  ],
};
